openapi: 3.0.1
info:
  title: monster-bulette
  x-cortex-tag: monster-bulette
  x-cortex-custom-metadata:
    alignment: lawful-neutral
    type: monstrosity
    challenge_rating: 27
    legendary: false
    armor_class: 17
    hit_points: 247
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-bulette
      alias: github-token-test
